### ISSUE TITLE
[my_except_hook:379]        [CRITICAL] | Uncaught Exception

### ISSUE THREAD

**Issue by travisboss** [hotio/qbitmanage#8]
```
Traceback (most recent call last):
  File "/app/qbit_manage.py", line 685, in <module>
    start_loop()
  File "/app/qbit_manage.py", line 401, in start_loop
    start()
  File "/app/qbit_manage.py", line 477, in start
    stats["categorized"] += Category(qbit_manager).stats
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/modules/core/category.py", line 19, in __init__
    self.category()
  File "/app/modules/core/category.py", line 29, in category
    new_cat.extend(self.get_tracker_cat(torrent) or self.qbt.get_category(torrent.save_path))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/modules/qbittorrent.py", line 375, in get_category
    if os.path.join(save_path, "") == path:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not CommentedMap
```

Updated to the latest version of qbitmanage and am now getting this error?  It will kill the script and try to start and just go in a constant loop.

**Comment by travisboss** [comment]
Moving back to `release-4.1.4` did stop this error.

**Comment by mrhotio** [comment]
Can't reproduce with a clean install and no idea why you would be submitting app bug reports here...unless you know it's because of a missing dependency, nor do I know why you're spamming in multiple places?
